### ISSUE TITLE
Clone saved layout

### ISSUE THREAD

**Issue by BlueSpaceCanary** [bdejesus/xiv-bars#114]
First of all, thanks for the awesome tool! 🙂 It's been really helpful for homogenizing my layouts across different jobs in the same role, and for experimenting with ways to work around the awkwardness of dpad targeting + dpad hotbar.

ANYWAY the actual FR: I mostly use the site for tracking / comparing changes to my hotbar layouts that I'm testing out, so it'd be nice to have a way to duplicate a saved layout to a new slot & then edit that while preserving the old one.

As an alternative, a way to get the unsaved/logged-out URL corresponding to a saved layout would also work since you could grab that URL, edit from that, and save it as a new layout.

I'd offer to throw together a PR for this myself, but I have almost no web dev (or js in general) experience, sorry 🙁

**Comment by bdejesus** [comment]
This feature has been added! You'll now see a "Copy Layout" button when viewing a saved layout which will copy the slots into a new layout that can be saved to a new slot.
