### ISSUE TITLE
Clicking my layouts shows an error message

### ISSUE THREAD

**Issue by seattle713** [bdejesus/xiv-bars#123]
The error shown is:
_APPLICATION ERROR: A CLIENT-SIDE EXCEPTION HAS OCCURRED (SEE THE BROWSER CONSOLE FOR MORE INFORMATION)._
I'm wondering if it might be that there are too many sets saved since I didn't "publish" them all as I went through them and then tried to at the end, and it capped the number of sets? I tried erasing cookies and history and cache, but it didn't do anything. I would like to be able to delete some sets off my account but the error shows up when I go to that page.

**Comment by bdejesus** [comment]
Hi @seattle713 thanks for reporting this. I've fixed the bug causing this error in https://github.com/bdejesus/xiv-bars/commit/6b44154f815df210c2eb5836dbd51d7d0d17089b and increased the max limit for saved layouts to 18.
