### ISSUE TITLE
Cannot save layout

### ISSUE THREAD

**Issue by ValenBree** [bdejesus/xiv-bars#125]
I have a bunch of saved urls from before the update was made to save layouts to your linked discord account.  I'd like to save all of these layouts to my account, rather than create them all from scratch, but when I click the "publish" button to save one of these existing layouts, I get "Couldn’t save layout. Please try again."

**Comment by bdejesus** [comment]
hey @ValenBree do you have a share url that you can post as an example?

**Comment by ValenBree** [comment]
Hopefully this works?  As you can see in the screenshot, I'm logged into my discord but when I hit publish I get this error.  If I go to "My Layouts" first, then begin a new layout and save it, that works fine.  The trouble is I have 19 layouts that I'd love to save to my account but I'd rather not build them all from scratch.

https://xivbars.bejezus.com/job/PLD?s1=3541,7382,r7537,r7533,24,16457,7381,16461,r7531,25746,22,17,3538,3539,15,9,r7538,28,g3,r7548,r7540,m25,30,g4,7383,25747,20,23,16460,16459,16458,7384,c59,c58,m31,m57,m62,m25,m26,g4,m65,m56,m72,m59,3540,7385,r7535,27,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0&xhb=1&wxhb=3&exhb=2






On Tuesday, January 10, 2023 at 04:37:50 PM EST, Benedicto de Jesus ***@***.***> wrote: 







hey @ValenBree do you have a share url that you can post as an example?

**Comment by bdejesus** [comment]
Thanks for reporting this issue, it should now be fixed!

**Comment by ValenBree** [comment]
That worked! Thank you, but now that I've loaded all my classes hotbars I noticed another issue: there's only room for 18 saved layouts but there are 19 battle jobs (20 if you count BLU, 24 including MIN BTN FSH and a crafter) is there any way to increase the number of layouts you can save?






On Thursday, January 12, 2023 at 01:41:58 AM EST, Benedicto de Jesus ***@***.***> wrote: 







Closed #125 as completed.

**Comment by bdejesus** [comment]
I've upped the limit to 30, thanks again!
