### ISSUE TITLE
Allow browsing other peoples' configurations

### ISSUE THREAD

**Issue by ChrisWeiss** [bdejesus/xiv-bars#128]
It would be very handy to be able to brows other peoples' submissions to see what strategies they might be using.
What would make this extra powerful would be an option to thumbsup/thumbsdown and to sort the output by likes.
Not sure how you'd present this in the UI.

**Comment by bdejesus** [comment]
I've added a list view for browsing others configurations - thumbsup/down will come with a later update. Thanks for the feedback!
