### ISSUE TITLE
Can't Publish Bars

### ISSUE THREAD

**Issue by 6hys** [bdejesus/xiv-bars#151]
Hiya. I don't seem to be able to publish any bars I create even though I've not got any saved yet. 

The button is greyed out here:
![image](https://github.com/bdejesus/xiv-bars/assets/13033766/24c6812c-8345-40dd-94c8-39746a45a9a4)

When I inspect the element in Chrome it has `title="You’ve reached your maximum alotted layouts. Delete others to publish new ones."` but it doesn't tell me this anywhere on the page itself.

As you can see, I have nothing saved/published yet:
![image](https://github.com/bdejesus/xiv-bars/assets/13033766/f85b7b52-faab-41f4-89ff-ccd02f46e1db)

I can copy [the URL for the bars](https://xivbars.bejezus.com/job/DRK/new?s1=g3,0,3629,0,0,0,r7535,16471,3634,3621,16468,3639,3625,7393,0,r7548,3638,0,0,3636,0,0,r7537,0,16466,16467,7392,7391,0,16472,3641,r7531,3640,r7538,0,25757,3617,3623,3632,0,0,7390,3643,25754,g4,r7540,r7533,3624,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0&xhb=1&wxhb=1&exhb=1&hb=4,1,1,1,1,1,1,1,1,1&l=1) and bookmark it though.

First time writing one of these, sorry if there's any information I missed!

**Comment by bdejesus** [comment]
Thanks for submitting this issue and providing details -- I've put in a fix and you should now be able publish your layouts.
