### ISSUE TITLE
Refactoring role actions to be fetched via XIVAPI

### ISSUE THREAD

**Issue by tokataka** [bdejesus/xiv-bars#201]
I've implemented getting role actions from API Instead of using ROLE_ACTION_IDS table.
Also I've added PvP common actions. (Still printed as Role Actions in app though)

You may try XIVAPI queries of those.

- PvE: [https://xivapi.com/search?indexes=Action,CraftAction&filters=ClassJobCategory.SAM=1,IsRoleAction=1](https://xivapi.com/search?indexes=Action&filters=ClassJobCategory.SAM=1,IsRoleAction=1)
- PvP: [https://xivapi.com/search?indexes=Action,CraftAction&filters=ClassJobCategoryTargetID=85,IsPlayerAction=1](https://xivapi.com/search?indexes=Action&filters=ClassJobCategoryTargetID=85,IsPlayerAction=1)

Note that `ClassJobCategoryTargetID=85` may or may not be changed in future patches.

**Comment by bdejesus** [comment]
Sweet! Just reviewed and merged your changes, thanks for your work on this!
