### ISSUE TITLE
Layouts not saving or updating

### ISSUE THREAD

**Issue by Acapella75** [bdejesus/xiv-bars#210]
I have attempted this on multiple browsers with all extensions disabled (Chrome, Firefox, Opera).

2 days ago, I was able to successfully create 2 layouts. I did not publish them, but saved as drafts. Today I went to create a 3rd layout, After placing my abilities, naming the layout (no description given so it should save as draft), I get a red banner saying layout could not be saved. If I press the save button again, I get a green layout save successful banner. When I check my layouts, the layout is not there. 

This happens no matter which class I choose and also if I attempt to update my previous 2 saved layouts.

**Comment by bdejesus** [comment]
Thanks for reporting, this should now be fixed.

(https://github.com/bdejesus/xiv-bars/pull/212)
