### ISSUE TITLE
DoH classes display incomplete skill lists

### ISSUE THREAD

**Issue by klintworthde** [bdejesus/xiv-bars#22]
By my count, all crafting classes essentially have the same 34 skills (although one is only for Specialists and several have different icons). The planner currently only shows ten skills for all DoH classes.

The ten you choose seem to all share icons; however, not all cross-class skills still appear. For one, Name of the Elements displays while Brand of the Elements does not.

As a quick query of the database you're drawing from, a la

> search?filters=ClassJob.ID=10&string=

seems to show all of the skills, something must be going wrong with fetching them.

**Comment by bdejesus** [comment]
Thanks for reporting! The initial implementation was a bit hacky, just so I could get most of the actions up. I finally found some time to revisit this and clean up the API requests and should now be returning the complete actions list for all classes.

7f71f60f69c9de082f64edec21bce3c64e985751
