### ISSUE TITLE
Macro Button issue

### ISSUE THREAD

**Issue by Nicolas-GE** [bdejesus/xiv-bars#220]
**Describe the bug**
When the macro button is pressed, it doesn't work correctly and doesn't display over the XHB icons
there is also no obvious option to close it besides refreshing the page

**To Reproduce**
1. Go to a XHB page (https://xivbars.bejezus.com/job/SGE/2536 for example)
2. Click on the macro button

**Expected behavior**
the macro popup appears above everything or on top of the left side with all the info

**Screenshots**

**Environment (please complete the following information if relevant):**
 - OS: Windows 10
 - Chrome Version 123.0.6312.106 (Official Build) (64-bit)

**Additional context or notes**
this issue is not exclusive to XHB, but it's where i encountered it first

**Comment by bdejesus** [comment]
This should now be fixed!
