### ISSUE TITLE
Role Color/jobstone icons

### ISSUE THREAD

**Issue by Nicolas-GE** [bdejesus/xiv-bars#232]
when i browse my configs they're all white text on black backgrounds and it takes me an embarassing amount of time to find which one is which

it'd be cool if the icons could be colored based on role (blue,green,red) or based on the Soul Stones

**Additional context**

here's a mockup i quickly and jankily made
![image](https://github.com/bdejesus/xiv-bars/assets/42648527/a0d9ed80-a02b-486d-a1c3-e1ed21951fe6)

**Comment by bdejesus** [comment]
thanks for the feedback and the mockup, here's what I'm working on to address this:

![image](https://github.com/bdejesus/xiv-bars/assets/5114/8f9e56a6-f48c-41c8-9f07-fdb4ae6a41cb)
I want to avoid having the screen just be a mosaic of colors, so for now I'm just adding the color to the icon. Hopefully it's enough to make it easy to distinguish which layout is which.

**Comment by Nicolas-GE** [comment]
love the edit! as you can tell im not a UX designer X)
