### ISSUE TITLE
PCT and VPR

### ISSUE THREAD

**Issue by talisein** [bdejesus/xiv-bars#245]
Does the site still support the custom actions you setup for SGE and RPR before EW launch? Is there anything a contributor might do to help you?

**Comment by bdejesus** [comment]
Yes! If you're familiar with Javascript, data can be stubbed in for `PCT` and `VPR`.

`data/JobsMeta.json` is where static ClassJob properties live. These properties get merged with xivapi data and written into the `./apiData` output folder, which the app reads from. (Some VPR and PCT props are already stubbed in at [the bottom of that file](https://github.com/bdejesus/xiv-bars/blob/main/data/JobsMeta.json#L362-L387))

For custom actions, we'd need the array of actions for PCT/VPR, ideally in JSON format (Action props are defined in [`types/Action.d.ts#L1-L16`](https://github.com/bdejesus/xiv-bars/blob/main/types/Action.d.ts#L1-L16)). To stub custom Actions for PCT and VPR, the [`pages/api/actions.ts`](https://github.com/bdejesus/xiv-bars/blob/main/pages/api/actions.ts#L7) endpoint can be updated to return a custom JSON source file if the request asks for PCT or VPR – for example:

```js
  let file;

  if (job === 'PCT') {
    file = `/data/JobActions/PCT.json`;
  } else {
    file = `${defaultFilePath}/${job}.json`;
  }
```

**Comment by talisein** [comment]
I stubbed out one action to get a feel for it and have it running on my local machine. lmk if there's anything you don't like in this general format before I add the rest of the actions. talisein/xiv-bars#1

**Comment by bdejesus** [comment]
I took a look, and it looks good to me! 👍🏼

**Comment by bdejesus** [comment]
Amazing! Thanks for the contributions @talisein @dethstroak 🚀
