### ISSUE TITLE
Feature Request: Generate Macros

### ISSUE THREAD

**Issue by hx41455** [bdejesus/xiv-bars#37]
If possible, could you add the ability to generate in-game macros from the planner layout?

**Comment by bdejesus** [comment]
Hey @hx41455 can you give more details on what the expected behavior would be for this feature (like input/output)? I just want to make sure I understand what this is supposed to do.

**Comment by hx41455** [comment]
Basically I'm looking to turn a planned layout into a set of in-game macros that places those abilities/spells onto the hotbars/crossbars. And additionally for BLU, a second set of macros to activate those spells in the spellbook.


What I'm envisioning for the page is another button that would open a window that was populated with a list of macros, generated by the ability/spell placements on the planner. If you're familiar with teamcraft's craft simulator, it has a similar function where after creating a crafting rotation there is a button that opens a window with a list of macros of that rotation to paste into the game.

**Comment by bdejesus** [comment]
I love this idea, and will look into it! Thanks for submitting this.

**Comment by bdejesus** [comment]
I pushed out an update that adds macros support for the layout. From the quick research I did, it looks like not all action types are supported by the `/hotbars` subcommands (menus, company actions, etc) so I just grayed them out and indicated that they are not supported.

**Comment by hx41455** [comment]
Awesome! Thank you!
