### ISSUE TITLE
General actions not displaying when using the url link. 

### ISSUE THREAD

**Issue by kashi-venka** [bdejesus/xiv-bars#47]
Hello, 

Placing general actions ie "Limit Break" adds g3 to the url. However when using the link created the General action will not be displayed. 

Also it would be wonderful to add a potion icon to the list of available actions, as pots are frequently used and position if pots on ones Hotbar is important for ease of use during ones opener. 
Thank you for your consideration.

Best, 
Kashi

**Comment by bdejesus** [comment]
Hi Kashi,

Thanks for reporting this issue, I'll take a look and fix the URL issue and adding general use items like potions.

**Comment by kashi-venka** [comment]
Thank you for your hard work! On Apr 27, 2021 10:24, Benedicto de Jesus ***@***.***> wrote:
Hi Kashi,
Thanks for reporting this issue, I'll take a look and fix the URL issue and adding general use items like potions.

**Comment by bdejesus** [comment]
Fixed in https://github.com/bdejesus/xiv-bars/commit/a7f168032b7ede1797b993addac0bcf3adb31829 - and created a new ticket for addtion Potions as available actions (https://github.com/bdejesus/xiv-bars/issues/480)
