### ISSUE TITLE
Add Reaper and Sage as supported Jobs.

### ISSUE THREAD

**Issue by Vulasuw** [bdejesus/xiv-bars#66]
The embargo has been lifted yesterday. I assume this is already in the works (or planned, at least), so please ignore if so!

**Comment by bdejesus** [comment]
Hi @Vulasuw, the app fetches data from xivapi.com, but it looks like the data around Reaper and Sage are still unavailable (I do see that there are placeholders for them). They should become available as soon as xivapi.com updates their api.

**Comment by bdejesus** [comment]
Sage and Reaper has been added in this update #71.
