### ISSUE TITLE
Sage & Reaper

### ISSUE THREAD

**Issue by Vemtran** [bdejesus/xiv-bars#67]
Hoping can be updated to show new jobs Sage and Reaper.

https://gamerescape.com/2021/10/13/final-fantasy-xiv-endwalker-hands-on-with-sage/
https://gamerescape.com/2021/10/13/final-fantasy-xiv-endwalker-hands-on-with-reaper/

**Comment by bdejesus** [comment]
The app fetches data from xivapi, but it looks like the data around Reaper and Sage are still unavailable (I do see that there are placeholders for them). They should become available as soon as xivapi.com updates their api.

**Comment by bdejesus** [comment]
Sage and Reaper has been added in this update #71.
