### ISSUE TITLE
SGE and RPR?

### ISSUE THREAD

**Issue by Wilford111** [bdejesus/xiv-bars#68]
Hello, are there any plans for the near future to include Sage and Reaper jobs in the website?
Thank you

**Comment by bdejesus** [comment]
The app fetches data from xivapi, but it looks like the data around Reaper and Sage are still unavailable (I do see that there are placeholders for them). They should become available as soon as xivapi.com updates their api.

**Comment by bdejesus** [comment]
Sage and Reaper has been added in this update #71.
