### ISSUE TITLE
Not updated for Reaper/Sage

### ISSUE THREAD

**Issue by ferrisaj87** [bdejesus/xiv-bars#69]
And I think it should be :D

Lots of ability details out now https://www.reddit.com/r/ffxiv/comments/qib72w/endwalker_new_jobs_including_smn_hotbar_planning/

**Comment by bdejesus** [comment]
Thanks for sharing the link! I've added Sage and Reaper in a pre-release state, which should mostly work but can change or break once Endwalker comes out.
