### ISSUE TITLE
Option for visual hotbar layout style?

### ISSUE THREAD

**Issue by zjhendryx** [bdejesus/xiv-bars#70]
When planning out our hotbars, we often may wish to do so based on how our hotbars will look in game.
The hotbar options allows each bar to be 12x1 (the default), 6x2, 4x3, 3x4, 2x6, and 1x12
Currently the only hotbar layout you display is the 12x1.
Would there be any change that your online tool could be updated to allow us to also change the layout of each hotbar to one of the in game supported layout, so as to help us visually see how our actions would be positioned next to each other please?

**Comment by Rina-Y** [comment]
Also same thing with the cross hotbar, it has a version where the inner two crosses are swapped in the settings and kind of makes it hard to set them up when your brain thinks one thing and the app needs another.

**Comment by bdejesus** [comment]
Took me a while to get to this, but I've added Hotbar layout options. The layouts can get a little weird, but it works well enough for now. As for the cross hotbar options, I'll look into getting that in when I find more time.

**Comment by bdejesus** [comment]
Moving the second part of this issue to it's own ticket to prioritize. Closing this issue as the initial request has been addressed.
