### ISSUE TITLE
Add toggle ability names display

### ISSUE THREAD

**Issue by ThatsSoTrinda** [bdejesus/xiv-bars#74]
I don't know all of the abilities by their icons yet. Is it possible to add a toggle that will add the ability name below its respective icon?

**Comment by bdejesus** [comment]
Hi @ThatsSoTrinda, thanks for the feedback! I've added a button to toggle the visibility of Action Names:

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/5114/140628453-21316bb0-096e-4dcb-9f86-8f8b3a5bc9a3.png">
