### ISSUE TITLE
Missing Class Job Actions

### ISSUE THREAD

**Issue by drhouse** [bdejesus/xiv-bars#80]
**Describe the bug**
Multiple classes are missing their job actions, presuming this is not due to the Endwalker expansion, i.e. this is not about Reaper or Sage

**To Reproduce**
[Machinist](https://xivbars.bejezus.com/?job=MCH&l=1)
[Dark Knight](https://xivbars.bejezus.com/?job=DRK&l=1)
etc...
missing job actions

**Expected behavior**
[Bard](https://xivbars.bejezus.com/?job=BRD&l=1) for example, has all its class's Job Actions at upper-left, as do some other classes

**Comment by bdejesus** [comment]
Thanks for reporting this issue. With the Endwalker update, a lot of underlying data has changed causing these kinds of thing breaking. I'm currently looking into fixing this, but the app currently depends on xivapi for sourcing Class and Action data. Will update when this can be resolved.

**Comment by bdejesus** [comment]
XIVAPI has resolved the issue w/ missing Job Actions data. Closing this issue.
