### ISSUE TITLE
XHB labeling for WXHB/Expanded

### ISSUE THREAD

**Issue by Squintina** [bdejesus/xiv-bars#81]
**Is your feature request related to a problem? Please describe.**
Not a problem, just informational

**Describe the solution you'd like**
Right now the "WXHB" section lists sets 1,2,3, (+ to 8).
First, I need to point out that WXHB specifically means Double Cross Hotbar (In Japanese, "W" and "Double" are both pronounced "Da-buru" so that's how the naming for W = Double came to be). The regular cross hotbar sets are just called XHB.
But the feature request would be to label a set as being part of WHXB or Expanded. This would help people visualize the setup better.

**Describe alternatives you've considered**
The alternative is to explain this outside of the site.

**Additional context**
WXHB (double tap) and Expanded (L2+R2) fundamentally change how a person accesses their hotbars, so a visual indicator of which sets are being used as part of WXHB and Expanded would make it more shareable so other people viewing the linked set can understand what is going on.

**Comment by bdejesus** [comment]
@Squintina thanks for your feedback! Based on this, I've added controls to be able to assign hotbars as being the Main XHB, WXHB, and Expanded hotbars, which sets how the hotbars are laid out on the screen.
