### ISSUE TITLE
Ability list not showing up

### ISSUE THREAD

**Issue by platypusshauni** [bdejesus/xiv-bars#94]
The ability list on the left no longer shows up for me at all.

**Comment by platypusshauni** [comment]
More details: I'm on android. Tried entering the site both through old links with finished crossbars and from google, didn't fix the issue. Also tried swapping which job was selected but no luck.

**Comment by platypusshauni** [comment]
Now it's back

**Comment by bdejesus** [comment]
Thanks for submitting! Yeah I pushed out some updates that broke some of the layout for mobile screens. Those changes have been reverted this should be working again.
